#!/bin/sh
if [ -z "$1" ]; then
    echo "Usage: $0 weeknum [verbose]"
    echo "Extract scores for the given week and upload to the homework assignment in Canvas"
    echo "Scores are expected to be generated by nbgrader and stored in ./grades.csv"
    echo "Run verbosely if the optional second argument is non-empty"
    exit 1
fi

#dryrun="-n"
week=$1
[ -n "$2" ] && verbose="-v"

python py4ds.py $dryrun $verbose -a "Week $week | Assignment" --week $week -H grades.csv
